# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Files/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Va_Main(object):
    def setupUi(self, Va_Main):
        Va_Main.setObjectName("Va_Main")
        Va_Main.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Va_Main)
        self.centralwidget.setObjectName("centralwidget")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 90, 781, 221))
        self.openGLWidget.setObjectName("openGLWidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 340, 781, 211))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 181, 51))
        self.label.setObjectName("label")
        Va_Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Va_Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menuoptions = QtWidgets.QMenu(self.menubar)
        self.menuoptions.setObjectName("menuoptions")
        Va_Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Va_Main)
        self.statusbar.setObjectName("statusbar")
        Va_Main.setStatusBar(self.statusbar)
        self.actionabout = QtWidgets.QAction(Va_Main)
        self.actionabout.setObjectName("actionabout")
        self.menuoptions.addAction(self.actionabout)
        self.menubar.addAction(self.menuoptions.menuAction())

        self.retranslateUi(Va_Main)
        QtCore.QMetaObject.connectSlotsByName(Va_Main)

    def retranslateUi(self, Va_Main):
        _translate = QtCore.QCoreApplication.translate
        Va_Main.setWindowTitle(_translate("Va_Main", "MainWindow"))
        self.label.setText(_translate("Va_Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; text-decoration: underline; color:#3584e4;\">J.A.R.V.I.S</span></p></body></html>"))
        self.menuoptions.setTitle(_translate("Va_Main", "options"))
        self.actionabout.setText(_translate("Va_Main", "about"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Va_Main = QtWidgets.QMainWindow()
    ui = Ui_Va_Main()
    ui.setupUi(Va_Main)
    Va_Main.show()
    sys.exit(app.exec_())
